## K-means CLustering Algorithm

K-Means clustering is an unsupervised learning algorithm which automatically cluster similar data points together.

K-Means is an iterative procedure that    
* Starts by guessing the initial centroids.    
* Repeatedly assigning data points to their closest centroids.  
* Recomputing the new centroids by calculating the mean of each cluster using the points assigned to it.     
* The K-means algorithm will always converges to some final set of means for the centroids.   
 


* However, that the converged solution may not always be ideal and depends on the initial setting of the centroids.
    * Therefore, in practice the K-means algorithm is usually run a few times with different random initializations. 
    * One way to choose between these different solutions from different random initializations is to choose the one with the lowest cost function value (distortion).

#### Implementation of K-Means clustering from scratch

In first phase of the K-means algorithm, the
algorithm assigns every training example $x^{(i)}$ to its closest
centroid, given the current positions of centroids.    
In order to assign points we are going to create a helper function (`find_closest_centroids`).      

* This function takes the data matrix `X` and the locations of all
centroids inside `centroids` 
* It should output a one-dimensional array `idx` (which has the same number of elements as `X`) that holds the index  of the closest centroid (a value in $\{1,...,K\}$, where $K$ is total number of centroids) to every training example .
* Specifically, for every example $x^{(i)}$ we set
$$c^{(i)} := j \quad \mathrm{that \; minimizes} \quad ||x^{(i)} - \mu_j||^2,$$
where 
 * $c^{(i)}$ is the index of the centroid that is closest to $x^{(i)}$ (corresponds to `idx[i]` in the starter code), and 
 * $\mu_j$ is the position (value) of the $j$’th centroid. (stored in `centroids` in the starter code)
 

Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:

def find_closest_centroids(X, centroids):
    
    n = X.shape[0]
    idx = np.zeros(X.shape[0], dtype=int) # idx store the cluster number of data points
    for i in range(n):
        a = centroids-X[i]
        b = np.linalg.norm(a,axis=1) # L2 norm
        idx[i]=np.argmin(b) # getting the closest cluster centroid
    
    return idx


In [3]:

initial_centroids = np.array([[2,4], [2,1], [8,5]])
np.random.seed(1)
x = np.random.randint(0,10,(10,2))
idx = find_closest_centroids(x,initial_centroids)
print("idx",idx)

idx [2 2 1 0 2 0 1 1 0 2]


In the second phase of the algorithm we are going to find new centroids by taking the mean of newly assigned points to the clusters.   
in order to find the mean we are going to create a helper function (`compute_centroids`) 

In [4]:

def compute_centroids(X, idx, K):
    
    m, n = X.shape
    centroids = np.zeros((K, n))
    for i in range(K):
        a = np.where(idx == i)
        points = X[a]
        centroids[i] = np.mean(points,axis=0) # calculating the new centroid from newly assigned data points
    
    return centroids

In [5]:
K = 3 # number of clusters
centroids = compute_centroids(x, idx, K)

print("The centroids are:", centroids)

The centroids are: [[2.33333333 6.        ]
 [3.         1.33333333]
 [6.75       7.75      ]]


Random initialization of centroids points

In [6]:
def init_centroids(x,K):
    rand_idx = np.random.permutation(x.shape[0])
    centroids = x[rand_idx[:K]] # random initialization of K centroids 

    return centroids

To work on K-Means clustsering we will import Iris dataset for convenience    
Iris dataset have four features with three different class types 

In [7]:
data = pd.read_csv("datasets/iris.csv")
data

5.1  3.5  1.4  0.2     setosa
0    4.9  3.0  1.4  0.2     setosa
1    4.7  3.2  1.3  0.2     setosa
2    4.6  3.1  1.5  0.2     setosa
3    5.0  3.6  1.4  0.2     setosa
4    5.4  3.9  1.7  0.4     setosa
..   ...  ...  ...  ...        ...
144  6.7  3.0  5.2  2.3  virginica
145  6.3  2.5  5.0  1.9  virginica
146  6.5  3.0  5.2  2.0  virginica
147  6.2  3.4  5.4  2.3  virginica
148  5.9  3.0  5.1  1.8  virginica

[149 rows x 5 columns]

#### Application of K-Means algorithm   


Image compression with K-Means algorithm    

* In a straightforward 24-bit color representation of an image, each pixel is represented as three 8-bit unsigned integers (ranging from 0 to 255) that specify the red, green and blue intensity values. This encoding is often refered to as the RGB encoding.
* Here you will reduce the number of colors to K colors.
* By making this reduction, it is possible to represent (compress) the photo in an efficient way. 
* Specifically, you only need to store the RGB values of the `K` selected colors, and for each pixel in the image you now need to only store the index of the color at that location.

In this part, you will use the K-means algorithm to select the `K` colors that will be used to represent the compressed image.
* Concretely, you will treat every pixel in the original image as a data example and use the K-means algorithm to find the 16 colors that best group (cluster) the pixels in the 3- dimensional RGB space. 
* Once you have computed the cluster centroids on the image, you will then use the `K` colors to replace the pixels in the original image.


In [2]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("datasets/iris.csv",names=["f1","f2","f3","f4","class"])

In [6]:
df.head()

f1   f2   f3   f4   class
0  5.1  3.5  1.4  0.2  setosa
1  4.9  3.0  1.4  0.2  setosa
2  4.7  3.2  1.3  0.2  setosa
3  4.6  3.1  1.5  0.2  setosa
4  5.0  3.6  1.4  0.2  setosa

In [7]:
x = df.drop("class",axis=1).values
y = df["class"].values
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [11]:
std = StandardScaler()
x_std = std.fit_transform(x_train)
x_std_t = std.transform(x_test)

In [17]:
cov_m = np.cov(x_std,rowvar=False)

In [19]:
cov_m

array([[ 1.00900901, -0.12657806,  0.87840152,  0.83069726],
       [-0.12657806,  1.00900901, -0.43680652, -0.3579596 ],
       [ 0.87840152, -0.43680652,  1.00900901,  0.97235153],
       [ 0.83069726, -0.3579596 ,  0.97235153,  1.00900901]])

In [29]:
eigen_val,eigen_vec = np.linalg.eigh(cov_m)
eigen_vec

array([[ 0.2461333 ,  0.72870494,  0.36845769, -0.52215558],
       [-0.12878427, -0.23193418,  0.92589298,  0.26896717],
       [-0.7994054 , -0.15504588,  0.01849996, -0.58014613],
       [ 0.53271382, -0.625425  ,  0.08135647, -0.56430549]])

In [28]:
eigen_vec[:, :-2-1:-1]

array([[-0.52215558,  0.36845769],
       [ 0.26896717,  0.92589298],
       [-0.58014613,  0.01849996],
       [-0.56430549,  0.08135647]])

In [25]:
np.max(eigen_vec,axis=0)

array([0.53271382, 0.72870494, 0.92589298, 0.26896717])